window.COUNTRIES = [
  { slug:"india", name:"Індія", flag:"🇮🇳", image:"images/india.jpg",
    short:"Життя на берегах Гангу, священні міста та стародавні традиції.",
    capital:"Нью-Делі", language:"гінді, англійська", currency:"індійська рупія", population:"1,4 млрд", bestTime:"жовтень — березень", episodes:16,
    description:["Одна з найвідоміших експедицій проєкту."],
    highlights:["Священні гати Варанасі","Пустеля Тар"],
    fact:"Саме індійські сезони зробили програму відомою далеко за межами України.",
    video: "https://www.youtube.com/embed/Yw-2mACvciA"
  },
  { slug:"nepal", name:"Непал", flag:"🇳🇵", image:"images/nepal.jpg",
    short:"Підніжжя Евересту, шерпи та суворі умови Гімалаїв.",
    capital:"Катманду", language:"непальська", currency:"непальська рупія", population:"30 млн", bestTime:"березень — травень, жовтень — листопад", episodes:15,
    description:["Подорож до підніжжя Евересту."],
    highlights:["Базовий табір Евереста","Ступа Сваямбунатх"],
    fact:"Частина зйомок проходила на висоті понад 5000 метрів.",
    video: "https://www.youtube.com/embed/ncou2XyXGDs"
  },
  { slug:"japan", name:"Японія", flag:"🇯🇵", image:"images/japan.jpg",
    short:"Країна майбутнього, самураїв та швидкісних поїздів.",
    capital:"Токіо", language:"японська", currency:"єна", population:"125 млн", bestTime:"березень — травень (сакура), листопад", episodes:15,
    description:["Країна майбутнього та традицій."],
    highlights:["Синкансен","Храми Кіото"],
    fact:"Японський сезон став одним із найпопулярніших.",
    video: "https://www.youtube.com/embed/YmhxIgrNwsU"
  },
  { slug:"china", name:"Китай", flag:"🇨🇳", image:"images/china.jpg",
    short:"Велика стіна, стародавні традиції та мегаполіси.",
    capital:"Пекін", language:"мандаринська", currency:"юань", population:"1,4 млрд", bestTime:"квітень — червень", episodes:33,
    description:["Велика китайська стіна та мегаполіси."],
    highlights:["Велика стіна","Заборонене місто"],
    fact:"Одна з наймасштабніших експедицій.",
    video: "https://www.youtube.com/embed/videoseries?list=PL4YcmB6duia9nslHqDLEiVuUvxOC-lnEN"
  },
  { slug:"pakistan", name:"Пакистан", flag:"🇵🇰", image:"images/pakistan.jpg",
    short:"Небезпечні дороги та краєвиди Каракоруму.",
    capital:"Ісламабад", language:"урду, англійська", currency:"пакистанська рупія", population:"240 млн", bestTime:"квітень — жовтень", episodes:22,
    description:["Каракорумське шосе та високогірні поселення."],
    highlights:["Каракорумське шосе","Долина Хунза"],
    fact:"Унікальні гірські ландшафти.",
    video: "https://www.youtube.com/embed/mqGSkDFeLEo"
  },
  { slug:"brazil", name:"Бразилія", flag:"🇧🇷", image:"images/brazil.jpg",
    short:"Амазонські джунглі, дикі племена та найбільша річка світу.",
    capital:"Бразиліа", language:"португальська", currency:"реал", population:"215 млн", bestTime:"травень — вересень", episodes:40,
    description:["Амазонія та фавели Ріо."],
    highlights:["Амазонка","Карнавал"],
    fact:"Широкий спектр культур та ландшафтів.",
    video: "https://www.youtube.com/embed/7fbljDHo2uM"
  },
  { slug:"bolivia", name:"Болівія", flag:"🇧🇴", image:"images/bolivia.jpg",
    short:"Солончак Уюні, дорога смерті та гори Анд.",
    capital:"Сукре (Ла-Пас)", language:"іспанська, кечуа, аймара", currency:"болівіано", population:"12 млн", bestTime:"травень — жовтень", episodes:14,
    description:["Солончак Уюні та гірські поселення."],
    highlights:["Солончак Уюні","Дорога смерті"],
    fact:"Багато високогірних знімальних локацій.",
    video: "https://www.youtube.com/embed/HE1vJaDJ3EE"
  },
  { slug:"ecuador", name:"Еквадор", flag:"🇪🇨", image:"images/ecuador.jpg",
    short:"Вулкани, екватор та дивовижна природа Анд.",
    capital:"Кіто", language:"іспанська", currency:"долар США", population:"18 млн", bestTime:"червень — вересень", episodes:48,
    description:["Галапагоські острови та екватор."],
    highlights:["Галапагоси","Вулкан Котопахі"],
    fact:"Різноманіття біосферних зон.",
    video: "https://www.youtube.com/embed/videoseries?list=PL4YcmB6duia8YwVKwA-euhHcYbE2Nx0BF"
  },
  { slug:"colombia", name:"Колумбія", flag:"🇨🇴", image:"images/colombia.jpg",
    short:"Барвисті міста, гори та кавові плантації.",
    capital:"Богота", language:"іспанська", currency:"колумбійський песо", population:"52 млн", bestTime:"грудень — березень", episodes:12,
    description:["Медельїн, кавові регіони та Картахена."],
    highlights:["Долина Кокора","Кавові плантації"],
    fact:"Колумбія — один із лідерів кавового виробництва.",
    video: "https://www.youtube.com/embed/videoseries?list=PLtNfyrM6LNlBL_SnlfwB7zSNJcwOqj53E"
  },
  { slug:"ethiopia", name:"Ефіопія", flag:"🇪🇹", image:"images/ethiopia.jpg",
    short:"Унікальні племена та стародавня історія.",
    capital:"Аддис-Абеба", language:"амхарська", currency:"етіопський бір", population:"120 млн", bestTime:"жовтень — травень", episodes:3,
    description:["Племена долини Омо та Лалібела."],
    highlights:["Племена долини Омо","Церкви Лалібели"],
    fact:"Глибока історична спадщина.",
    video: "https://www.youtube.com/embed/vSx2GJGTEcY"
  },
  { slug:"kenya", name:"Кенія", flag:"🇰🇪", image:"images/kenya.jpg",
    short:"Савани, сафарі та плем'я масаї.",
    capital:"Найробі", language:"суахілі, англійська", currency:"кенійський шилінг", population:"55 млн", bestTime:"липень — жовтень", episodes:15,
    description:["Сафари та Велика міграція."],
    highlights:["Масаї-Мара","Велика міграція"],
    fact:"Велика міграція — одне з найбільших природних явищ.",
    video: "https://www.youtube.com/embed/1qC6U20cwSs"
  },
  { slug:"indonesia", name:"Індонезія", flag:"🇮🇩", image:"images/indonesia.jpg",
    short:"Активні вулкани та екзотичні острови.",
    capital:"Джакарта", language:"індонезійська", currency:"рупія", population:"275 млн", bestTime:"травень — вересень", episodes:22,
    description:["Вулкани Іджен і культура Балі."],
    highlights:["Іджен","Комодо"],
    fact:"Найбільший архіпелаг у світі.",
    video: "https://www.youtube.com/embed/Ut5qrUrNPj0"
  },
  { slug:"vietnam", name:"В'єтнам", flag:"🇻🇳", image:"images/vietnam.jpg",
    short:"Рисові тераси, давні міста та унікальна кухня.",
    capital:"Ханой", language:"в'єтнамська", currency:"донг", population:"100 млн", bestTime:"листопад — квітень", episodes:19,
    description:["Халонг, Хойан і Сапа."],
    highlights:["Затока Халонг","Хойан"],
    fact:"Кухня В'єтнаму — одна з найвідоміших.",
    video: "https://www.youtube.com/embed/jf7rqXk751w"
  },
  { slug:"cambodia", name:"Камбоджа", flag:"🇰🇭", image:"images/cambodia.jpg",
    short:"Храмовий комплекс Ангкор та культура кхмерів.",
    capital:"Пномпень", language:"кхмерська", currency:"ріель", population:"17 млн", bestTime:"листопад — березень", episodes:7,
    description:["Ангкор-Ват та плаваючі села."],
    highlights:["Ангкор-Ват","Тонлесап"],
    fact:"Ангкор-Ват — унікальна спадщина.",
    video: "https://www.youtube.com/embed/hnjpcWQ5oeo"
  },
  { slug:"tanzania", name:"Танзанія", flag:"🇹🇿", image:"images/tanzania.jpg",
    short:"Кіліманджаро, Серенгеті та племена масаїв.",
    capital:"Додома", language:"суахілі", currency:"танзанійський шилінг", population:"65 млн", bestTime:"червень — жовтень", episodes:7,
    description:["Серенгеті і Кіліманджаро."],
    highlights:["Кіліманджаро","Серенгеті"],
    fact:"Неймовірні ландшафти та сафарі.",
    video: "https://www.youtube.com/embed/FDFd8kiZRxk"
  },
  { slug:"ukraine", name:"Україна", flag:"🇺🇦", image:"images/ukraine.jpg",
    short:"Карпати, культура та природні пам'ятки України.",
    capital:"Київ", language:"українська", currency:"гривня", population:"40 млн", bestTime:"травень — вересень", episodes:20,
    description:["Карпати, Синевир та гуцульські традиції."],
    highlights:["Говерла","Синевир"],
    fact:"Особливі випуски присвячені Україні.",
    video: "https://www.youtube.com/embed/6n7POXj6wYY"
  },
  { slug:"cuba", name:"Куба", flag:"🇨🇺", image:"images/cuba.jpg",
    short:"Острів свободи, ретро-авто та колоніальна архітектура.",
    capital:"Гавана", language:"іспанська", currency:"кубанське песо", population:"11 млн", bestTime:"листопад — квітень", episodes:9,
    description:["Ретро-авто та музика Куби."],
    highlights:["Стара Гавана","Малекон"],
    fact:"Куба славиться своєю музикою та архітектурою.",
    video: "https://www.youtube.com/embed/4OXyhdKGMHk"
  },
  { slug:"mexico", name:"Мексика", flag:"🇲🇽", image:"images/mexico.jpg",
    short:"Піраміди майя, барвисті міста та традиційна кухня.",
    capital:"Мехіко", language:"іспанська", currency:"мексиканське песо", population:"130 млн", bestTime:"листопад — квітень", episodes:7,
    description:["Майя, Оахака і кухонні традиції."],
    highlights:["Чичен-Іца","Оахака"],
    fact:"Мексиканська кухня — культурна спадщина.",
    video: "https://www.youtube.com/embed/yxGOMDk9Ftw"
  }
];
